### ISSUE TITLE
Compile fail: unknown register name 'r0' in asm

### ISSUE THREAD

**Issue by hqt** [MindMac/AndroidEagleEye#8]
When I compile using ndk-build I meet this exception:

```
jni/base/hook.c:43:5: error: unknown register name 'r0' in asm
                :       "r0", "r1", "r7"
```

For this method:

```
void inline hook_cacheflush(unsigned int begin, unsigned int end)
{

	const int syscall = 0xf0002;
	__asm __volatile (
		"mov	 r0, %0\n"			
		"mov	 r1, %1\n"
		"mov	 r7, %2\n"
		"mov     r2, #0x0\n"
		"svc     0x00000000\n"
		:
		:	"r" (begin), "r" (end), "r" (syscall)
		:	"r0", "r1", "r7"
		);

}
```

Do you have any idea for fixing this. thanks.

**Comment by MindMac** [comment]
What's the ndk version you used to build? Please try to use a latest one

**Comment by hqt** [comment]
thanks. I have fixed this problem. I config for building only on arm. Build on x86 and mips will cause above problem.

**Comment by ttimasdf** [comment]
@hqt I added `TARGET_ARCH_ABI := armeabi armeabi-v7a` to Android.mk but the error persists. How do you solve it?

**Comment by MindMac** [comment]
@ttimasdf The native hook is not stable, if there is no need for the native hook part. Please disable the native compilation part. Or you can refer to this answer https://stackoverflow.com/questions/41335345/android-ndk-build-error-unknown-register-name-r0-in-asm, but I am not sure it works. It seems you need to update the Application.mk file.

**Comment by ttimasdf** [comment]
@MindMac Hi, I saw this post as well.  I've figured out a solution by either add `APP_ABI=armeabi-v7a` in ndk-build command line, or add `ndk.abiFilters 'armeabi-v7a'` in build.gradle according to [this](https://developer.android.com/studio/projects/add-native-code.html) (I was building with Android Studio). Now the build have passed, I'll try it out tomorrow....it's been too late out here. 😨
